### ISSUE TITLE
Rooting the device

### ISSUE THREAD

**Issue by Lyubna** [seemoo-lab/nexmon#54]
Hello,
I am working on Android emulator (Nexus5 API) and when I launch the app it asks me to root the device, I tried installing the app on the device itself too, it says "we need root to proceed", but you mentioned in the description that it doesn't need rooting, why am I getting this?

**Comment by matthiasseemoo** [comment]
where exactly did we mention that nexmon does not need root?

Am 08.03.2017 1:02 nachm. schrieb "Lyubna" <notifications@github.com>:

**Comment by Lyubna** [comment]
![capture](https://cloud.githubusercontent.com/assets/18594914/23704165/406089b4-040c-11e7-893f-16f066920d98.PNG)
Well , the screenshot is took from the description.

**Comment by Lyubna** [comment]
![capture](https://cloud.githubusercontent.com/assets/18594914/23704233/908449f8-040c-11e7-960e-2b2799e5f7c7.PNG)
In the screenshot, it says you can do it without root privileges

**Comment by matthiasseemoo** [comment]
That is the special case to communicate with the firmware without root
priviledges. the intension is to allow apps to control the firmware without
having root priviledges, however, you first nees root to install the
firmware and then you need root to set a security cookie in the firmware,
otherwise every non-root app would have access to control the firmware.

btw. it does not make sense to try the firmware hack in the amdroid
emulator, as the wifi chip will not be emulated.

Am 08.03.2017 1:36 nachm. schrieb "Lyubna" <notifications@github.com>:
