### ISSUE TITLE
How to Install on Asus RT-AX86U Pro

### ISSUE THREAD

**Issue by abyz01** [seemoo-lab/nexmon#593]
I would like to request support for installing on the Asus RT-AX86U Pro. Is the usage similar to that of a Raspberry Pi?

thank you

**Comment by jlinktu** [comment]
_Please note that we currently only support the 5 GHz interface of the Asus RT-AX86U Pro and the current nexmon firmware doesn't come with any advanced features. Also, the default firmware for the Asus RT-AX86U Pro already supports monitor mode, if this is what you are looking for. Check out the `wl` util that comes pre-installed together with the official Asus system._

If you still want to build and install the nexmon firmware:  
Follow the [README here](https://github.com/seemoo-lab/nexmon?tab=readme-ov-file#build-patches-for-bcm4330-bcm4339-and-bcm4358-using-a-x86-computer-running-linux-eg-ubuntu-1604) up to the last bullet point. Instead of the last point do the following:
- change into directory of the firmware for the Asus RT-AX86U Pro `cd patches/bcm6715b0/17_10_188_6401_r808804_ax86upro/nexmon`.
- build the firmware: `make`.
- create a destination directory **on your Asus RT-AX86U Pro**, e.g. `/jffs/nexmon`.
- move the firmware file `rtecdc.bin` over **to your Asus RT-AX86U Pro** into the previously created directory, e.g. to `/jffs/nexmon/rtecdc.bin`. _(**)_
- **on your Asus RT-AX86U Pro**  
  1. remove the kernel module for the 5 GHz interface: `/sbin/rmmod dhd`.
  1. load the kernel module pointing it to the modified firmware: `/sbin/insmod $(find /lib/modules -name dhd.ko) firmware_path=/jffs/nexmon/rtecdc.bin instance_base=1`.
  1. configure the interface (`eth7`), either manually using `wl` and `ifconfig`, or if you want to use the defaults using `/sbin/restart_wireless`.  
    
 _(**)_ _On recent builds by Asus, there seem to be no `scp` and tools like `wget` do not accept IPv4 addresses. One way to transfer files is to open a web server on your local machine in the nexmon folder where `rtecdc.bin` is located by running `python3 -m http.server 8080` and on the Asus router, map your local IPV4 address (e.g. 192.168.50.100) to a host name, e.g. "mymachine", with `echo "192.168.50.100 mymachine" >> /etc/hosts`. Then on your Asus router you can fetch the file with: `cd /jffs/nexmon && wget http://mymachine:8080/rtecdc.bin`. Note that this is just one of many possible ways, you may want to do it differently._
